---
# tasks file for easy-pgbouncer
- name: Install OpenJDK on Operating System for RPM
  yum:
    name: pgbouncer
    state: present
  when: >-
    ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat
    Enterprise Linux'

- name: Install OpenJDK on Operating System for DEB
  apt:
    name: pgbouncer
    state: present
    update_cache: "yes"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Grant Permissions to pgbouncer directory for postgresql user
  file:
    path: /etc/pgbouncer/
    owner: postgres
    group: postgres
    mode: '0700'

- name: Grant Permissions to pgbouncer pid directory for postgresql user
  file:
    path: /var/run/pgbouncer/
    owner: postgres
    group: postgres
    mode: '0700'

- name: Grant Permissions to pgbouncer log directory for postgresql user
  file:
    path: /var/log/pgbouncer/
    owner: postgres
    group: postgres
    mode: '0700'